CREATE TABLE Sessions(
	Session_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Date DATETIME,
	NumberOfSoldTickets INT
);
CREATE TABLE Troupes(
	Troupe_ID INT IDENTITY NOT NULL PRIMARY KEY
);
CREATE TABLE Titles(
	Title_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(100)
);
CREATE TABLE Actors(
	Actor_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Surname VARCHAR(100),
	Name VARCHAR(100),
	Patronymic VARCHAR(100),
	Salary DECIMAL(10,2)
);
CREATE TABLE ActorsTitles(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Actor_ID INT, 
	FOREIGN KEY (Actor_ID) REFERENCES Actors(Actor_ID),
	Title_ID INT,
	FOREIGN KEY (Title_ID) REFERENCES Titles(Title_ID),
);
CREATE TABLE Importances(
	Importance_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(100)
);
CREATE TABLE Roles(
	Role_ID INT IDENTITY NOT NULL PRIMARY KEY,
	CharacterName VARCHAR(100)
);
CREATE TABLE RoleImportances(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Role_ID INT,
	FOREIGN KEY (Role_ID) REFERENCES Roles(Role_ID),
	Importance_ID INT,
	FOREIGN KEY (Importance_ID) REFERENCES ImportanceLevels(Importance_ID)
);
CREATE TABLE Plays(
	Play_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(100),
	Duration TIME(0)
);
CREATE TABLE PlayStatuses(
	PlayStatuses_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(100)
);
CREATE TABLE Repertoire(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Play_ID INT,
	FOREIGN KEY (Play_ID) REFERENCES Plays(Play_ID),
	PlayStatuses_ID INT,
	FOREIGN KEY (PlayStatuses_ID) REFERENCES PlayStatuses(PlayStatuses_ID)
);
CREATE TABLE PlayRoles(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Play_ID INT,
	FOREIGN KEY (Play_ID) REFERENCES Plays(Play_ID),
	Role_ID INT, 
	FOREIGN KEY (Role_ID) REFERENCES Roles(Role_ID)
);
CREATE TABLE TroupeComposition(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Troupe_ID INT,
	FOREIGN KEY (Troupe_ID) REFERENCES Troupes(Troupe_ID),
	Role_ID INT,
	FOREIGN KEY (Role_ID) REFERENCES Roles(Role_ID),
	MainActor_ID INT,
	FOREIGN KEY (MainActor_ID) REFERENCES Actors(Actor_ID),
	DoublerActor_ID INT,
	FOREIGN KEY (DoublerActor_ID) REFERENCES Actors(Actor_ID),
);
CREATE TABLE Submissions(
	Submission_ID INT IDENTITY NOT NULL PRIMARY KEY,
	Play_ID INT,
	FOREIGN KEY (Play_ID) REFERENCES Plays(Play_ID),
	Troupe_ID INT
	FOREIGN KEY (Troupe_ID) REFERENCES Troupes(Troupe_ID)
);
CREATE TABLE SessionSubmissions(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Session_ID INT,
	FOREIGN KEY (Session_ID) REFERENCES Sessions(Session_ID),
	Submission_ID INT,
	FOREIGN KEY (Submission_ID) REFERENCES Submissions(Submission_ID)
);